# Generated by Django 5.0.6 on 2024-07-18 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
        ("users", "0004_alter_payment_course_alter_payment_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.IntegerField(
                blank=True,
                help_text="Укажите ID сессии",
                null=True,
                verbose_name="ID сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите курс",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите урок",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.IntegerField(
                help_text="Укажите сумму оплаты", verbose_name="Сумма оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Наличные", "Наличные"),
                    ("Перевод на счет", "Перевод на счет"),
                ],
                help_text="Укажите тип оплаты",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                help_text="Укажите пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
